// 'use client';
import { Providers } from "./providers";

import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Railway FS Assessment",
  description: "Generated by Railway FS Assessment",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
